language: python
python:
  - "3.6"
  - "3.7"
cache:
  directories:
    - $HOME/.cache/pip
    - /opt/python
sudo: false
env:
  - TOX_ENV=py37-flake8
  - TOX_ENV=py36-dj22
  - TOX_ENV=py36-dj30
  - TOX_ENV=py37-dj22
  - TOX_ENV=py37-dj30
install:
  - pip install -r requirements-test.txt
script:
  - tox -e $TOX_ENV
