language: python
cache:
  directories:
    - $HOME/.cache/pip
    - /opt/python
sudo: false
env:
  - TOX_ENV=py37-flake8
  - TOX_ENV=py36-dj22
  - TOX_ENV=py36-dj30
  - TOX_ENV=py37-dj22
  - TOX_ENV=py37-dj30
before_install:
  - pyenv install 3.6 --skip-existing
  - pyenv install 3.7 --skip-existing
  - pyenv global system 3.7
install:
  - pip install -r requirements-test.txt
script:
  - tox -e $TOX_ENV
